
services:
  syncace:
    image: sync-ace
    container_name: syncace
    build: ./
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    env_file: ./.env
    ports:
      - '3030:3030'
    stdin_open: true
    tty: true

 